### ISSUE TITLE
Image Rebuild

### ISSUE THREAD

**Issue by JamsRepos** [criscrafter/JMusicBot-Unraid#4]
Hi,

A new version of the bot is out, could you please rebuild the image?

Thanks.

**Comment by criscrafter** [comment]
Yes, it's not that easy, because I have to Upgrade the Java Version as well.
In the worst Case I will do it on the Weekend.
Maybe before.
Greetings

**Comment by JamsRepos** [comment]
> Yes, it's not that easy, because I have to Upgrade the Java Version as well. In the worst Case I will do it on the Weekend. Maybe before. Greetings

No worries! Thanks for the quick response - no rush at all :)

**Comment by yellowcooln** [comment]
Thank you as well!

**Comment by Healzangels** [comment]
Came here interested about the update as well; awesome to hear and thanks for all the hard work!

**Comment by criscrafter** [comment]
It was way easier than expected.
The new update is published and you will see the update available in Unraid in the next few hours.
Have a nice rest of the week! :)

**Comment by criscrafter** [comment]
You can also press "check for updates" in the bottom of your unraid docker tab and update it now.

**Comment by yellowcooln** [comment]
Updated and tested working. Thank You!

![image](https://github.com/criscrafter/JMusicBot-Unraid/assets/12516003/59c03903-08c3-441d-969e-d742dd382c6b)
