### ISSUE TITLE
Outdated version (YT playback is now broken)

### ISSUE THREAD

**Issue by 2chriswy** [criscrafter/JMusicBot-Unraid#5]
Hey I am Just letting you know the new version of jmusic bot fixes the YT playback issues that are in the current version.

Thanks again for the awesome docker.

**Comment by criscrafter** [comment]
Yeah, Version 4.1 already fixed the biggest issues that 4.0 introduced.
I'll get around to it. Should be pretty easy.

**Comment by criscrafter** [comment]
Update is pushed.
Should show up in a few hours(Unraid Limitation) but you can also switch to advanced view(top right on the Docker page) and it will show "force update".
